import type { Category, MenuItem } from "./types"

export const mockCategories: Category[] = [
  {
    id: "1",
    name_en: "Main Dishes",
    name_fr: "Plats Principaux",
    description_en: "Hearty main courses",
    description_fr: "Plats principaux copieux",
    display_order: 1,
  },
  {
    id: "2",
    name_en: "Appetizers",
    name_fr: "Entrées",
    description_en: "Start your meal right",
    description_fr: "Commencez bien votre repas",
    display_order: 2,
  },
  {
    id: "3",
    name_en: "Desserts",
    name_fr: "Desserts",
    description_en: "Sweet treats",
    description_fr: "Douceurs sucrées",
    display_order: 3,
  },
  {
    id: "4",
    name_en: "Beverages",
    name_fr: "Boissons",
    description_en: "Refreshing drinks",
    description_fr: "Boissons rafraîchissantes",
    display_order: 4,
  },
]

export const mockMenuItems: MenuItem[] = [
  {
    id: "1",
    category_id: "1",
    name_en: "Grilled Chicken with Rice",
    name_fr: "Poulet Grillé avec Riz",
    description_en: "Tender grilled chicken served with seasoned rice and vegetables",
    description_fr: "Poulet grillé tendre servi avec du riz assaisonné et des légumes",
    price: 8500,
    image_url: "/grilled-chicken-with-rice-african-cuisine.jpg",
    is_available: true,
    preparation_time: 25,
  },
  {
    id: "2",
    category_id: "1",
    name_en: "Jollof Rice with Fish",
    name_fr: "Riz Jollof avec Poisson",
    description_en: "Traditional West African jollof rice with grilled fish",
    description_fr: "Riz jollof ouest-africain traditionnel avec poisson grillé",
    price: 9000,
    image_url: "/jollof-rice-with-fish-west-african.jpg",
    is_available: true,
    preparation_time: 30,
  },
  {
    id: "3",
    category_id: "1",
    name_en: "Beef Stew with Plantains",
    name_fr: "Ragoût de Boeuf avec Plantains",
    description_en: "Rich beef stew served with fried plantains",
    description_fr: "Ragoût de boeuf riche servi avec des plantains frits",
    price: 10000,
    image_url: "/beef-stew-with-fried-plantains-african.jpg",
    is_available: true,
    preparation_time: 35,
  },
  {
    id: "4",
    category_id: "2",
    name_en: "Spring Rolls",
    name_fr: "Rouleaux de Printemps",
    description_en: "Crispy vegetable spring rolls with sweet chili sauce",
    description_fr: "Rouleaux de printemps aux légumes croustillants avec sauce chili douce",
    price: 3000,
    image_url: "/crispy-spring-rolls-appetizer.jpg",
    is_available: true,
    preparation_time: 15,
  },
  {
    id: "5",
    category_id: "2",
    name_en: "Meat Samosas",
    name_fr: "Samosas à la Viande",
    description_en: "Spiced meat-filled pastries, perfectly fried",
    description_fr: "Pâtisseries farcies à la viande épicée, parfaitement frites",
    price: 2500,
    image_url: "/meat-samosas-fried-pastries.jpg",
    is_available: true,
    preparation_time: 15,
  },
  {
    id: "6",
    category_id: "3",
    name_en: "Chocolate Cake",
    name_fr: "Gâteau au Chocolat",
    description_en: "Rich chocolate cake with chocolate ganache",
    description_fr: "Gâteau au chocolat riche avec ganache au chocolat",
    price: 4000,
    image_url: "/rich-chocolate-cake-slice.jpg",
    is_available: true,
    preparation_time: 10,
  },
  {
    id: "7",
    category_id: "3",
    name_en: "Fruit Salad",
    name_fr: "Salade de Fruits",
    description_en: "Fresh seasonal fruits with honey drizzle",
    description_fr: "Fruits frais de saison avec filet de miel",
    price: 3500,
    image_url: "/fresh-fruit-salad-bowl.jpg",
    is_available: true,
    preparation_time: 10,
  },
  {
    id: "8",
    category_id: "4",
    name_en: "Fresh Orange Juice",
    name_fr: "Jus d'Orange Frais",
    description_en: "Freshly squeezed orange juice",
    description_fr: "Jus d'orange fraîchement pressé",
    price: 2000,
    image_url: "/fresh-orange-juice-glass.jpg",
    is_available: true,
    preparation_time: 5,
  },
  {
    id: "9",
    category_id: "4",
    name_en: "Iced Tea",
    name_fr: "Thé Glacé",
    description_en: "Refreshing iced tea with lemon",
    description_fr: "Thé glacé rafraîchissant au citron",
    price: 1500,
    image_url: "/iced-tea-with-lemon.png",
    is_available: true,
    preparation_time: 5,
  },
  {
    id: "10",
    category_id: "4",
    name_en: "Mineral Water",
    name_fr: "Eau Minérale",
    description_en: "Bottled mineral water",
    description_fr: "Eau minérale en bouteille",
    price: 1000,
    image_url: "/bottled-mineral-water.jpg",
    is_available: true,
    preparation_time: 2,
  },
]
